### PR TITLE
Feature/products categories

### PR DESCRIPTION
**Pull request by M-Pedrami**
Finished my section

### CODE REVIEW

**Review by Lukileila — APPROVED** [review]
Nice!

**Review by Pia-Koester — CHANGES_REQUESTED** [review]
Two minor things I have noticed: 
- in the original Design the Heading for "Check out the Store" is entirely orange
- the hover effect appears a bit wonky and wobbly, if you like it like this we can keep it but maybe make it a little bit more subtle?

**Comment by M-Pedrami** [comment]
> Two minor things I have noticed:
> 
> * in the original Design the Heading for "Check out the Store" is entirely orange
> * the hover effect appears a bit wonky and wobbly, if you like it like this we can keep it but maybe make it a little bit more subtle?

I accidentally changed it to orange on figma... it was originally black and orange

**Comment by M-Pedrami** [comment]
> > Two minor things I have noticed:
> > 
> > * in the original Design the Heading for "Check out the Store" is entirely orange
> > * the hover effect appears a bit wonky and wobbly, if you like it like this we can keep it but maybe make it a little bit more subtle?
> 
> I accidentally changed it to orange on figma... it was originally black and orange

I made it more subtle

**Review by Pia-Koester — APPROVED** [review]
Looks better without affecting the rest of the page now. Thank you @M-Pedrami

**Pull request merged**
